# Generated by Django 5.2.8 on 2025-11-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='priority',
            field=models.CharField(default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
