# Generated by Django 5.2.8 on 2025-11-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_alter_bug_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bug',
        ),
    ]
